# Reference-parity reproduction analysis (run from the package root).
#
# Quantifies how closely songR reproduces the original Python SONG, layer by
# layer, against the committed golden fixtures in
# tests/testthat/fixtures/reference/ (generated by gen_fixtures.py).
# Also writes the Procrustes overlay figure used in the reproduction article.
#
# Numerics are frozen: this script only MEASURES, it does not change songR.

suppressMessages({
  library(songR)
  library(aricode)
})

FX <- "tests/testthat/fixtures/reference/"
FIG <- "vignettes/articles/reference_parity_overlay.png"

ami <- function(emb, y, k) {
  mean(vapply(1:5, function(s) {
    set.seed(s)
    aricode::AMI(stats::kmeans(emb, k, nstart = 5, iter.max = 100)$cluster, y)
  }, numeric(1)))
}

# Optimal rotation + scale + translation aligning B onto A (Procrustes).
proc_align <- function(A, B) {
  A <- scale(A, scale = FALSE)
  B <- scale(B, scale = FALSE)
  sv <- svd(crossprod(B, A))
  (sum(sv$d) / sum(B^2)) * (B %*% (sv$u %*% t(sv$v)))
}
proc_r2 <- function(A, B) {
  Ba <- proc_align(A, B)
  1 - sum((scale(A, scale = FALSE) - Ba)^2) / sum(scale(A, scale = FALSE)^2)
}

# --- Tier A: deterministic kernels ---
A <- as.matrix(read.csv(paste0(FX, "tierA_A.csv"), header = FALSE))
B <- as.matrix(read.csv(paste0(FX, "tierA_B.csv"), header = FALSE))
ref_d <- as.matrix(read.csv(paste0(FX, "tierA_sqdist.csv"), header = FALSE))
song_d <- t(apply(A, 1, function(x) colSums((t(B) - x)^2)))
cat(sprintf("Tier A  sq-dist max abs err = %.2e ; argmin identical = %s\n",
            max(abs(song_d - ref_d)),
            all((apply(song_d, 1, which.min) - 1) ==
                  scan(paste0(FX, "tierA_argmin.csv"), quiet = TRUE))))

# --- Tier B nodisp: raw-space SONG on shared blobs ---
Xb <- as.matrix(read.csv(paste0(FX, "tierB_blobs_X.csv"), header = FALSE))
yb <- factor(scan(paste0(FX, "tierB_blobs_y.csv"), quiet = TRUE))
refB <- as.matrix(read.csv(paste0(FX, "tierB_blobs_emb_nodisp.csv"), header = FALSE))
mb <- song(Xb, d = 2L, k = 3L, epsilon = 0.99, epochs = 100L, a = 1.577, b = 0.895,
           spread_factor = 0.5, seed = 1L, dispersion = FALSE, verbose = FALSE)
cat(sprintf("Tier B nodisp  AMI ref=%.3f songR=%.3f | Procrustes R2=%.3f\n",
            ami(refB, yb, 8), ami(mb$embedding, yb, 8), proc_r2(refB, mb$embedding)))

# --- Tier B dispersed: UMAP back-end on MNIST (default mode) ---
Xm <- as.matrix(read.csv(paste0(FX, "tierB_mnist_X.csv"), header = FALSE))
ym <- factor(scan(paste0(FX, "tierB_mnist_y.csv"), quiet = TRUE))
refM <- as.matrix(read.csv(paste0(FX, "tierB_mnist_emb_umap.csv"), header = FALSE))
mm <- song(Xm, d = 2L, k = 3L, epsilon = 0.99, epochs = 100L, a = 1.577, b = 0.895,
           spread_factor = 0.5, seed = 1L, dispersion = TRUE, verbose = FALSE)
cat(sprintf("Tier B disp MNIST  AMI ref=%.3f songR=%.3f | Procrustes R2=%.3f\n",
            ami(refM, ym, 10), ami(mm$embedding, ym, 10), proc_r2(refM, mm$embedding)))

# --- Overlay figure (cached for the reproduction article) ---
grDevices::png(FIG, width = 1200, height = 1100, res = 120)
graphics::par(mfrow = c(2, 2), mar = c(3, 3, 3, 1))
p8 <- grDevices::hcl.colors(8, "Set 2")
p10 <- grDevices::hcl.colors(10, "Spectral")
plot(refB, col = p8[as.integer(yb)], pch = 16, cex = .5,
     main = "blobs nodisp - Reference (Python)", xlab = "", ylab = "")
plot(proc_align(refB, mb$embedding), col = p8[as.integer(yb)], pch = 16, cex = .5,
     main = sprintf("blobs nodisp - songR (aligned, R2=%.2f)", proc_r2(refB, mb$embedding)),
     xlab = "", ylab = "")
plot(refM, col = p10[as.integer(ym)], pch = 16, cex = .5,
     main = "MNIST dispersed - Reference (umap-learn)", xlab = "", ylab = "")
plot(proc_align(refM, mm$embedding), col = p10[as.integer(ym)], pch = 16, cex = .5,
     main = sprintf("MNIST dispersed - songR uwot (aligned, R2=%.2f)", proc_r2(refM, mm$embedding)),
     xlab = "", ylab = "")
grDevices::dev.off()
cat("Overlay figure written:", FIG, "\n")
