// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sq_euclidean_dist_cpp
double sq_euclidean_dist_cpp(const arma::rowvec& a, const arma::rowvec& b);
RcppExport SEXP _songR_sq_euclidean_dist_cpp(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::rowvec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(sq_euclidean_dist_cpp(a, b));
    return rcpp_result_gen;
END_RCPP
}
// euclidean_dist_cpp
double euclidean_dist_cpp(const arma::rowvec& a, const arma::rowvec& b);
RcppExport SEXP _songR_euclidean_dist_cpp(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::rowvec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(euclidean_dist_cpp(a, b));
    return rcpp_result_gen;
END_RCPP
}
// sq_dist_to_rows_cpp
arma::vec sq_dist_to_rows_cpp(const arma::rowvec& x, const arma::mat& M);
RcppExport SEXP _songR_sq_dist_to_rows_cpp(SEXP xSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::rowvec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(sq_dist_to_rows_cpp(x, M));
    return rcpp_result_gen;
END_RCPP
}
// knn_search_cpp
arma::uvec knn_search_cpp(const arma::rowvec& x, const arma::mat& C, int k);
RcppExport SEXP _songR_knn_search_cpp(SEXP xSEXP, SEXP CSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::rowvec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(knn_search_cpp(x, C, k));
    return rcpp_result_gen;
END_RCPP
}
// batch_knn_search_cpp
arma::umat batch_knn_search_cpp(const arma::mat& X, const arma::mat& C, int k);
RcppExport SEXP _songR_batch_knn_search_cpp(SEXP XSEXP, SEXP CSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(batch_knn_search_cpp(X, C, k));
    return rcpp_result_gen;
END_RCPP
}
// song_fit_cpp
Rcpp::List song_fit_cpp(const arma::mat& X, int d_out, int im_neix, double epsilon, int max_its, double lrst, double a_param, double b_param, double spread_factor, int ns_rate, double min_strength, int max_prototypes, double lr_sigma, bool verbose, int seed);
RcppExport SEXP _songR_song_fit_cpp(SEXP XSEXP, SEXP d_outSEXP, SEXP im_neixSEXP, SEXP epsilonSEXP, SEXP max_itsSEXP, SEXP lrstSEXP, SEXP a_paramSEXP, SEXP b_paramSEXP, SEXP spread_factorSEXP, SEXP ns_rateSEXP, SEXP min_strengthSEXP, SEXP max_prototypesSEXP, SEXP lr_sigmaSEXP, SEXP verboseSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type d_out(d_outSEXP);
    Rcpp::traits::input_parameter< int >::type im_neix(im_neixSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type max_its(max_itsSEXP);
    Rcpp::traits::input_parameter< double >::type lrst(lrstSEXP);
    Rcpp::traits::input_parameter< double >::type a_param(a_paramSEXP);
    Rcpp::traits::input_parameter< double >::type b_param(b_paramSEXP);
    Rcpp::traits::input_parameter< double >::type spread_factor(spread_factorSEXP);
    Rcpp::traits::input_parameter< int >::type ns_rate(ns_rateSEXP);
    Rcpp::traits::input_parameter< double >::type min_strength(min_strengthSEXP);
    Rcpp::traits::input_parameter< int >::type max_prototypes(max_prototypesSEXP);
    Rcpp::traits::input_parameter< double >::type lr_sigma(lr_sigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(song_fit_cpp(X, d_out, im_neix, epsilon, max_its, lrst, a_param, b_param, spread_factor, ns_rate, min_strength, max_prototypes, lr_sigma, verbose, seed));
    return rcpp_result_gen;
END_RCPP
}
// song_update_cpp
Rcpp::List song_update_cpp(const arma::mat& X_new, arma::mat W, arma::mat Y, arma::mat adj_in, arma::vec E_q_in, int d_out, int im_neix, double epsilon, int max_its, double lrst, double a_param, double b_param, double spread_factor, int ns_rate, double min_strength, int max_prototypes, double lr_sigma, bool verbose, int seed);
RcppExport SEXP _songR_song_update_cpp(SEXP X_newSEXP, SEXP WSEXP, SEXP YSEXP, SEXP adj_inSEXP, SEXP E_q_inSEXP, SEXP d_outSEXP, SEXP im_neixSEXP, SEXP epsilonSEXP, SEXP max_itsSEXP, SEXP lrstSEXP, SEXP a_paramSEXP, SEXP b_paramSEXP, SEXP spread_factorSEXP, SEXP ns_rateSEXP, SEXP min_strengthSEXP, SEXP max_prototypesSEXP, SEXP lr_sigmaSEXP, SEXP verboseSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_new(X_newSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type adj_in(adj_inSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type E_q_in(E_q_inSEXP);
    Rcpp::traits::input_parameter< int >::type d_out(d_outSEXP);
    Rcpp::traits::input_parameter< int >::type im_neix(im_neixSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type max_its(max_itsSEXP);
    Rcpp::traits::input_parameter< double >::type lrst(lrstSEXP);
    Rcpp::traits::input_parameter< double >::type a_param(a_paramSEXP);
    Rcpp::traits::input_parameter< double >::type b_param(b_paramSEXP);
    Rcpp::traits::input_parameter< double >::type spread_factor(spread_factorSEXP);
    Rcpp::traits::input_parameter< int >::type ns_rate(ns_rateSEXP);
    Rcpp::traits::input_parameter< double >::type min_strength(min_strengthSEXP);
    Rcpp::traits::input_parameter< int >::type max_prototypes(max_prototypesSEXP);
    Rcpp::traits::input_parameter< double >::type lr_sigma(lr_sigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(song_update_cpp(X_new, W, Y, adj_in, E_q_in, d_out, im_neix, epsilon, max_its, lrst, a_param, b_param, spread_factor, ns_rate, min_strength, max_prototypes, lr_sigma, verbose, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_songR_sq_euclidean_dist_cpp", (DL_FUNC) &_songR_sq_euclidean_dist_cpp, 2},
    {"_songR_euclidean_dist_cpp", (DL_FUNC) &_songR_euclidean_dist_cpp, 2},
    {"_songR_sq_dist_to_rows_cpp", (DL_FUNC) &_songR_sq_dist_to_rows_cpp, 2},
    {"_songR_knn_search_cpp", (DL_FUNC) &_songR_knn_search_cpp, 3},
    {"_songR_batch_knn_search_cpp", (DL_FUNC) &_songR_batch_knn_search_cpp, 3},
    {"_songR_song_fit_cpp", (DL_FUNC) &_songR_song_fit_cpp, 15},
    {"_songR_song_update_cpp", (DL_FUNC) &_songR_song_update_cpp, 19},
    {NULL, NULL, 0}
};

RcppExport void R_init_songR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
