# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sq_euclidean_dist_cpp <- function(a, b) {
    .Call(`_songR_sq_euclidean_dist_cpp`, a, b)
}

euclidean_dist_cpp <- function(a, b) {
    .Call(`_songR_euclidean_dist_cpp`, a, b)
}

sq_dist_to_rows_cpp <- function(x, M) {
    .Call(`_songR_sq_dist_to_rows_cpp`, x, M)
}

knn_search_cpp <- function(x, C, k) {
    .Call(`_songR_knn_search_cpp`, x, C, k)
}

batch_knn_search_cpp <- function(X, C, k) {
    .Call(`_songR_batch_knn_search_cpp`, X, C, k)
}

song_fit_cpp <- function(X, d_out, im_neix, epsilon, max_its, lrst, a_param, b_param, spread_factor, ns_rate, min_strength, max_prototypes, lr_sigma, verbose, seed) {
    .Call(`_songR_song_fit_cpp`, X, d_out, im_neix, epsilon, max_its, lrst, a_param, b_param, spread_factor, ns_rate, min_strength, max_prototypes, lr_sigma, verbose, seed)
}

song_update_cpp <- function(X_new, W, Y, adj_in, E_q_in, d_out, im_neix, epsilon, max_its, lrst, a_param, b_param, spread_factor, ns_rate, min_strength, max_prototypes, lr_sigma, verbose, seed) {
    .Call(`_songR_song_update_cpp`, X_new, W, Y, adj_in, E_q_in, d_out, im_neix, epsilon, max_its, lrst, a_param, b_param, spread_factor, ns_rate, min_strength, max_prototypes, lr_sigma, verbose, seed)
}

